[workspace]
resolver = "2"
members = [
 "libnvme-sys",
 "libnvme-sys/header-check",
 "libnvme"
]

default-members = [
 "libnvme-sys",
 "libnvme"
]

exclude = [
 "libnvme-sys/header-check"
]

[workspace.dependencies]
libnvme-sys = { path = "libnvme-sys" }
thiserror = "1.0.51"
