[workspace]
resolver = "2"
members = [
 "libnvme-sys",
 "libnvme"
]

[workspace.dependencies]
libnvme-sys = { path = "libnvme-sys" }
strum = { version = "0.26", features = ["derive"] }
strum_macros = "0.26"
thiserror = "1.0.51"
