[workspace]
resolver = "2"
members = [
 "nvme-sys",
 "nvme-sys/header-check",
 "nvme"
]

default-members = [
 "nvme-sys",
 "nvme"
]

exclude = [
 "nvme-sys/header-check"
]

[workspace.dependencies]
nvme-sys = { path = "nvme-sys" }
thiserror = "1.0.51"
