[package]
name = "libnvme"
version = "0.1.0"
license = "MPL-2.0"
edition = "2021"

[dependencies]
libnvme-sys.workspace = true
strum.workspace = true
strum_macros.workspace = true
thiserror.workspace = true
